### ISSUE TITLE
SwitchBtn not defined

### ISSUE THREAD

**Issue by smenzer** [gitbrent/bootstrap-switch-button#10]
Uncaught ReferenceError: SwitchBtn is not defined error showing up pointing to this line. Possible that it's because the class `SwitchBtn` class is defined above inside a `(function())` and so not available outside of that?

https://github.com/gitbrent/bootstrap-switch-button/blob/45b96770fadaed1bc7a7d276f4fc37c7ccaccca1/js/bootstrap-switch-button.js#L247

**Comment by mandersondesign** [comment]
Same issue here. Looks like this has been resolved in https://github.com/gitbrent/bootstrap-switch-button/pull/8 but @gitbrent has not merged that quite yet. 

I would love to see that knocked out, as I am using a forked/modified version right now and would love to just use the normal one pulled via npm.

Thanks!

**Comment by gitbrent** [comment]
See: Issue #8

**Comment by gitbrent** [comment]
@smenzer - thanks for reporting this.

Fixed with recent checkin. Releasing soon with v1.1
