### ISSUE TITLE
Wrong size on first div

### ISSUE THREAD

**Issue by tedebus** [gitbrent/bootstrap-switch-button#2]
Hi,
I don't understand why my result has 0px values on width and height style values.
I tried to copy your code:
`<input type="checkbox" data-toggle="switchbutton" checked data-onlabel="Ready" data-offlabel="Not Ready" data-onstyle="success" data-offstyle="danger">`

This is my result:
**`<div class="switch btn btn-success" style="width: 0px; height: 0px;">`**
`<input type="checkbox" data-toggle="switchbutton" checked="" data-onlabel="Ready" data-offlabel="Not Ready" data-onstyle="success" data-offstyle="danger">`
`<div class="switch-group">`
`<label class="btn btn-success btn- switch-on">Ready</label>`
`<label class="btn btn-danger btn- switch-off">Not Ready</label>`
`<span class="switch-handle btn btn-light btn-"></span>`
`</div>`
`</div>`

while in your demo page is this:

**`<div class="switch btn btn-success" style="width: 112.922px; height: 38px;">`**
`<input type="checkbox" data-toggle="switchbutton" checked="" data-onlabel="Ready" data-offlabel="Not Ready" data-onstyle="success" data-offstyle="danger">`
`<div class="switch-group">`
`<label class="btn btn-success btn- switch-on">Ready</label>`
`<label class="btn btn-danger btn- switch-off">Not Ready</label>`
`<span class="switch-handle btn btn-light btn-">`
`</span>`
`</div>`
`</div>`

I'm using it on a row->column of bootstrap 4.3
I see that css and js files you give as CDN are not exactly the one you used on our demo page, so I tried to change them copying your one on my project but result remains the same.

`<script src="https://gitbrent.github.io/bootstrap-switch-button/js/bootstrap-switch-button.js"></script>`
 `<link rel="stylesheet" href="https://gitbrent.github.io/bootstrap-switch-button/css/bootstrap-switch-button.css" crossorigin="anonymous">`
  

I'm also using "bootstrap-table", I don't know if it can be useful to know.
My IDE confirms that both css and js are available.
What's going wrong?
How can I solve?
Thank you in advance.

**Comment by gitbrent** [comment]
Hi @tedebus 

Is the switch-button visible when the page loads or when you initialize it?

**Comment by tedebus** [comment]
Yes, but I see it shorter. 
I read only "Read" ("y" missing) or "Not " ("ready" missing).
I can't show you now with a screenshot because (I'm sorry) I removed your lib from my project. I was hurry to complete my work.
