### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by kushal-g** [gitbrent/bootstrap-switch-button#6]
I've been trying to attach a .change() listener to switchbutton but I'm not able to do so. On trying out the documentation, I found that even the example code doesn't seem to be working.

```
<input id="switch-event" type="checkbox" data-toggle="switchbutton">
<div id="console-event"></div>
<script>
  $(function() {
    $('#switch-event').change(function() {
      $('#console-event').html('Checked?: ' + $(this).prop('checked'))
    })
  })
</script>
```

Neither is it working on my project, nor on the official website for this repo
[Bootstrap Switch Button](https://gitbrent.github.io/bootstrap-switch-button/)

Are there going to be any fixes in the foreseeable future?

**Comment by walidbagh** [comment]
I can confirm this issue. 
The only event that fires according to devtools on latest chrome is the click event.
It works just fine with the jquery distribution tho.

**Comment by walidbagh** [comment]
hey @kushal-g ,
i made a fix for this issue, feel free to check the pull request ~~#7~~ ---> #8 .
i hope it will be merged soon.

**Comment by meirboccara** [comment]
Hello, i up this topic.
Event don't work and when i want no dependency i don't want to use     $('#switch-event').change(function() which is jquery

**Comment by gitbrent** [comment]
@kushal-g - thanks for reporting this.

Fixed with recent checkin. Releasing soon with v1.1

![Feb-15-2020 23-21-56](https://user-images.githubusercontent.com/7218970/74599575-19455e80-504a-11ea-8b26-bf09d6f836e7.gif)
